### ISSUE TITLE
mixin support

### ISSUE THREAD

**Issue by francescoagati** [Glidias/haxevx#5]
hi,
i have see in the code that there is a macro mixin? there is a support on macrobuild for vue mixins?

**Comment by Glidias** [comment]
Nope. Not yet. A macro solution isn't available yet as mentioned in the roadmap under the KIV list...and I'm not sure what's the best way to go about it if some strict typing is to be kept. (ie. perhaps at least allow typehinting of mixed-in computed properties and methods?)....and the ability for the macro directive to have the flexibility  to only mix-in specific stuff from other classes that would be deemed relavent to each user's case. Mixins in general, are very dynamic. If you do mixins, you'd would likely have to take the manual untyped `this["mixins"]=[]` approach for now. I may include a basic base helper function in the future to facilitate this.

**Comment by francescoagati** [comment]
yes for now mixin manual is the best solution.

**Comment by francescoagati** [comment]
for some mixins i have used the lib partials

**Comment by Glidias** [comment]
Assuming that no runtime custom merge strategies are being used, (ie. stick to VueJS conventions), then some macroing and type hinting will actually be possible (though it might be a good option to allow them to set `false` on the mixin directive to disable typehinting field generation and go fully dynamic. A proposed possible format is to apply compile-time `@:mixin` metadata to your VComponent class implementation as follows, supplying a plain object definition for the 1st parameter:

Mock example:

	@:mixin({
            // mixin misc methods/getters/setters only via infering of field type
		_: PaginationOf.gotoNextPageMethod,	
		_: PaginationOf.gotoPrevPageMethod,
		_: AnotherClass.someFieldGetter,
		"customMethodFieldName": AnotherClass.gotoNextPageMethod,

         //  mixin vuejs specifics
		data: PaginationOf,  
		computed: [PaginationOf.someField, PaginationOf.someField2, AnotherClass2],	
		methods: {	
			_: PaginationOf.someMethod,
			_: PaginationOf.someMethod2,
			"customPropertyName": SomeClass.someMethodName
		},  
		props: [PropsSetA, PropSetB.field1, PropSetC.field2, PropSetD]
	})

You can automatically mixin an entire class' data, computed, methods, props, etc. by simply stating out the class definition without any adjoining property access on the given class for a given `computed/methods/data` key. (like in `data` as shown in example). 

For mixing-in of `data` however, if the class requires manual instantation due to specific constructor parameters, you can instantiate them via the new keyword instead of simply stating out the plain class definition (otherwise, an attempt to auto-instantatiate without supplying any constructor parameters will be done). Besides direct instantation (especially for typedefs), you can use a static function factory method call with a return data type signature, and pass in any constant parameters (if required) into the static function call that can be resolved at macro time.  For untyped anonymous data objects, some form of infering of field types via macro may still be possible....given the field values.

Non literal keys on objects (ie. those not enclosed in quotes) represent the standard keys for Vue component options that can be mixed in accordingly such as `computed`, `data`, `props`, etc..

If there is a given property access, then the macro will only attempt to fish out that field only from that given class. Thus, you can do partials in this manner. If mixing-in through an object instead of an array, using the `_` as a key will use the original field name, but using a literal `"customFieldName"` will use a custom field name for that given partial reference. 

Typehinting is available via generation of plain `var fieldName(default, default/never):Type` fields, since  you will fishing out actual fields from actual classes or typedefs, etc.  (but without needing their Expr implementations), just their type signature and field name. Do note that for method to be mixed in,, the class may need to incorporate a IBuildlisted marker interface to allow macro recording of function build field argument signatures, as I can't seem to find a way to easily and remotely retrieve function arguments otherwise.

As per convention, if the existing VComponent  class implementation already has such a field, it will not attempt to mixin those fields. Some warnings will be shown if a particular field explicitly requested in mixins is already declared in the VComponent class.

Another possible flag option for the mixin directive could allow Haxe to internally assert at compile time:  no duplication of fields across all attempted mixins regardless, or could auto-namespace them for you to avoid naming conflicts.

Since it's compile-time metadata, you can just use multiple `@:mixin` metadata directives to mixin multiple object definitions accordingly.

**Comment by francescoagati** [comment]
yes or we can use haxe inheritance for extends components?

**Comment by Glidias** [comment]
Haven't supported  it with inheritance yet but it should be pretty easy to setup with a few adjustments made to the components' _Init method to support Super calls to the base before merge overwrite obj properties with current class. Generally though, I wouldn't recommend inheritance as its more restrictive. Additionally, if you go the inheritance route, certain param types like Data and Prop must remain consistent and cannot be overloaded to something else, unlike the use of mixins which allows you to construct a composite type from multiple resources.

**Comment by francescoagati** [comment]
yes is true but in some situations can help

**Comment by Glidias** [comment]
Ok, did up support for inheritance (among other things like allowed inheritance+generic fieldtype tracing for `D,P` types as well when mixing in those fields into native Vue...). On the git repository, there should be support for inheritance along VComponent and VxComponent now. Do try it out and see if there are any issues. One thing to take note, only the single "base" class immediately succeeding `VComponent` or `VxComponent`, is the only class allowed to define the standard `D,P`/`S,D,P` type parameters. For simplicity, any extended classes will make use of those base type parameters with no means of overriding/overloading their type signatures. Eg. You can obviously override `Data():D` to return a different set of data from the previous implementation, but have to keep the same `D` type declared by the base class. If all goes well, i'd likely push this update to HaxeLib.

On a sidenote, I have experimental support for `@:vueIncludeDataMethods` and `IBuildListed` combo (which i'm using in production as well), to also allow accessing a Data class' methods/getters/setters  as native Vue methods/getters/setters, within a `V(x)Component` locally without remotely accessing them through Data class' API through `_vData` . This allows you to easily incorporate platform agnostic viewmodel code that may had originally been designed in an object-oriented manner, into the Native vueJS format.  eg. https://github.com/Glidias/haxevx/blob/master/src/haxevx/vuex/examples/pagination/model/PaginationOf.hx   . By adopting this approach, you can create viewmodel codebases that may also apply to non-JS/ non-Vue environments. Having this in combination with the @:mixin feature, would allow far more versatility in composing yr Vue components in HaxeVx, while keeping full type safety/hinting. Such a method of mixing in is described in: https://github.com/Glidias/haxevx/wiki/Design-Doc:-HaxeVx-mixins-for-VueJS#class-mixin-as-data-module

**Comment by francescoagati** [comment]
i think the solution for data wrapping with generic is complex. i must create a wrapper for data. mixin is a solution more simple when you need only to  inject new fields and methods

**Comment by Glidias** [comment]
Yup, will attempt mixins in the future. 

For Haxe, there are some considerations when doing mixins...

Design doc for mixins can be found at:
https://github.com/Glidias/haxevx/wiki/Design-Doc:-HaxeVx-mixins-for-VueJS
